[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
dotenv = "0.15.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
service = { path = "../service" }
entity = { path = "../entity" }

